// Code generated by mockery v2.49.1. DO NOT EDIT.

package mocks

import (
	dbmodels "github.com/norbix/demo1_fullstack_golang/backend/internal/db/dbmodels"
	mock "github.com/stretchr/testify/mock"
)

// AccountService is an autogenerated mock type for the AccountService type
type AccountService struct {
	mock.Mock
}

type AccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountService) EXPECT() *AccountService_Expecter {
	return &AccountService_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function with given fields: _a0
func (_m *AccountService) CreateAccount(_a0 dbmodels.Account) (map[string]interface{}, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(dbmodels.Account) (map[string]interface{}, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(dbmodels.Account) map[string]interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(dbmodels.Account) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountService_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type AccountService_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - _a0 dbmodels.Account
func (_e *AccountService_Expecter) CreateAccount(_a0 interface{}) *AccountService_CreateAccount_Call {
	return &AccountService_CreateAccount_Call{Call: _e.mock.On("CreateAccount", _a0)}
}

func (_c *AccountService_CreateAccount_Call) Run(run func(_a0 dbmodels.Account)) *AccountService_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(dbmodels.Account))
	})
	return _c
}

func (_c *AccountService_CreateAccount_Call) Return(_a0 map[string]interface{}, _a1 error) *AccountService_CreateAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountService_CreateAccount_Call) RunAndReturn(run func(dbmodels.Account) (map[string]interface{}, error)) *AccountService_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccounts provides a mock function with given fields: _a0, _a1
func (_m *AccountService) GetAccounts(_a0 int, _a1 int) (map[string]interface{}, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetAccounts")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (map[string]interface{}, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(int, int) map[string]interface{}); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountService_GetAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccounts'
type AccountService_GetAccounts_Call struct {
	*mock.Call
}

// GetAccounts is a helper method to define mock.On call
//   - _a0 int
//   - _a1 int
func (_e *AccountService_Expecter) GetAccounts(_a0 interface{}, _a1 interface{}) *AccountService_GetAccounts_Call {
	return &AccountService_GetAccounts_Call{Call: _e.mock.On("GetAccounts", _a0, _a1)}
}

func (_c *AccountService_GetAccounts_Call) Run(run func(_a0 int, _a1 int)) *AccountService_GetAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *AccountService_GetAccounts_Call) Return(_a0 map[string]interface{}, _a1 error) *AccountService_GetAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountService_GetAccounts_Call) RunAndReturn(run func(int, int) (map[string]interface{}, error)) *AccountService_GetAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountService creates a new instance of AccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountService {
	mock := &AccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
