---
version: '3.9'

services:
    backend:
        build:
            context: ..
            dockerfile: docker/backend/Dockerfile
        container_name: backend-service
        ports:
            - "8080:8080"
        environment:
            - ENV=production

    frontend:
        build:
            context: ..
            dockerfile: docker/frontend/Dockerfile
        container_name: frontend-service
        ports:
            - "3000:3000"
        depends_on:
            -   backend
        environment:
            - ENV=production
...
