version: '3.9'

services:
    backend:
        build:
            context: ..
            dockerfile: docker/backend/Dockerfile
        container_name: backend-service
        ports:
            - "8080:8080"
        env_file:
          - docker/backend/.env
        environment:
            - ENV=production
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
            interval: 30s
            timeout: 10s
            retries: 3
        networks:
          - app-network

    frontend:
        build:
            context: ..
            dockerfile: docker/frontend/Dockerfile
        container_name: frontend-service
        ports:
            - "3000:3000"
        env_file:
          - docker/frontend/.env
# TODO: Add depends_on
        environment:
            - ENV=production
        networks:
          - app-network
 
networks:
  app-network:
    driver: bridge

